### ISSUE TITLE
Strange behavior when using custom serializers

### ISSUE THREAD

**Issue by youroff** [danielspaniel/ember-data-factory-guy#223]
We use custom serializers for some models in order to reject some attributes from the payload. For example, we have `created_at` generated on server, but we definitely don't want it to be present in the payload. So we use it like following:
```
StockSerializer = ApplicationSerializer.extend
  attrs:
    created_at:
      serialize: false
```

But it breaks data generation by FactoryGuy somehow. When calling `make('stock')` we observe `[object Object]: null` instead of created_at. Is that expected behavior and how to deal with such cases?

UPD: Also with this model 'PATCH' request stays unhandled. Can this be related? I didn't get through code thoroughly, but I assume that updateMethod gets selected at the time when FixtureBuilder gets instantiated by the factory.
